In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df_train=pd.read_csv("train.csv")
df_train

Unnamed: 0  Division  Time  home_team  away_team  full_time_home_goals  \
0               0         0   NaN        152        426                     0   
1               1         0   NaN        216        341                     2   
2               2         0   NaN        223        119                     2   
3               3         0   NaN         68        137                     2   
4               4         1   NaN        425        225                     2   
...           ...       ...   ...        ...        ...                   ...   
39987       39995        15   NaN        231        309                     0   
39988       39996        15   NaN        248        398                     4   
39989       39997        15   NaN        453        126                     1   
39990       39998        13   NaN        164        403                     2   
39991       39999         6   NaN        271        269                     1   

       full_time_away_goals  half_time_home_goals  half_time_away_goals  \
0                         0                     0                     0   
1                         2                     0                     1   
2                         2                     2                     0   
3                         1                     0                     1   
4                         2                     1                     0   
...                     ...                   ...                   ...   
39987                     1                     0                     0   
39988                     0                     2                     0   
39989                     2                     1                     1   
39990                     2                     1                     2   
39991                     1                     0                     0   

       Referee  ...  home_corners  away_corners  home_yellow_cards  \
0           -1  ...           NaN           NaN                NaN   
1           -1  ...           NaN           NaN                NaN   
2           -1  ...           NaN           NaN                NaN   
3           -1  ...           NaN           NaN                NaN   
4           -1  ...           4.0          10.0                3.0   
...        ...  ...           ...           ...                ...   
39987       -1  ...           3.0           3.0                3.0   
39988       -1  ...           8.0           4.0                1.0   
39989       -1  ...           6.0           5.0                2.0   
39990       -1  ...           5.0           7.0                0.0   
39991       -1  ...           2.0           2.0                2.0   

       away_yellow_cards  home_red_cards  away_red_cards  home_coef  \
0                    NaN             NaN             NaN   3.627690   
1                    NaN             NaN             NaN   1.608321   
2                    NaN             NaN             NaN   2.166811   
3                    NaN             NaN             NaN   2.259244   
4                    4.0             1.0             0.0   2.424278   
...                  ...             ...             ...        ...   
39987                1.0             0.0             0.0   2.102645   
39988                2.0             0.0             0.0   1.340170   
39989                0.0             0.0             0.0   1.963689   
39990                0.0             0.0             0.0   4.050577   
39991                3.0             0.0             0.0   1.732761   

       draw_coef  away_coef  away_shots_on_target.1  
0       3.577721   2.198600                     NaN  
1       4.251999   6.533805                     NaN  
2       3.486596   3.821467                     NaN  
3       3.592401   3.460103                     NaN  
4       3.414191   3.282876               -1.032101  
...          ...        ...                     ...  
39987   3.404282   4.155226               -0.049414  
39988  

In [9]:
df_train=df_train.drop('Unnamed: 0',axis=1)

In [10]:
df_train['Referee']

0       -1
1       -1
2       -1
3       -1
4       -1
        ..
39987   -1
39988   -1
39989   -1
39990   -1
39991   -1
Name: Referee, Length: 39992, dtype: int64

In [11]:
df_train['Referee'].isna().sum()#otherwise retuen -1

0

In [12]:
len(df_train)

39992

In [13]:
df_train.isna().sum()

Division                      0
Time                      39992
home_team                     0
away_team                     0
full_time_home_goals          0
full_time_away_goals          0
half_time_home_goals          0
half_time_away_goals          0
Referee                       0
home_shots                15594
away_shots                15594
home_shots_on_target      15594
away_shots_on_target      15594
home_fouls                16344
away_fouls                16344
home_corners              15594
away_corners              15594
home_yellow_cards         15595
away_yellow_cards         15594
home_red_cards            15594
away_red_cards            15594
home_coef                     0
draw_coef                     0
away_coef                     0
away_shots_on_target.1    15594
dtype: int64

In [14]:
#before the match
df_train.Time=df_train.Time.fillna('-1')
df_train.Time=df_train.Time.astype(int)
df_train.Time

0       -1
1       -1
2       -1
3       -1
4       -1
        ..
39987   -1
39988   -1
39989   -1
39990   -1
39991   -1
Name: Time, Length: 39992, dtype: int32

In [15]:
df_train.dtypes

Division                    int64
Time                        int32
home_team                   int64
away_team                   int64
full_time_home_goals        int64
full_time_away_goals        int64
half_time_home_goals        int64
half_time_away_goals        int64
Referee                     int64
home_shots                float64
away_shots                float64
home_shots_on_target      float64
away_shots_on_target      float64
home_fouls                float64
away_fouls                float64
home_corners              float64
away_corners              float64
home_yellow_cards         float64
away_yellow_cards         float64
home_red_cards            float64
away_red_cards            float64
home_coef                 float64
draw_coef                 float64
away_coef                 float64
away_shots_on_target.1    float64
dtype: object

In [16]:
#dtype selection
category=['Division','Referee','Time']
numeric=['home_team','away_team','full_time_home_goals','full_time_away_goals','half_time_home_goals','half_time_away_goals','home_shots','away_shots','home_shots_on_target','away_shots_on_target','home_fouls','away_fouls','home_corners','away_corners','home_yellow_cards','away_yellow_cards','home_red_cards','away_red_cards']
floating=['home_coef','draw_coef','away_coef']

In [17]:
#refree and time =-1
respective=['full_time_home_goals','full_time_away_goals','half_time_home_goals','half_time_away_goals','Division','Time','home_team','away_team','Referee','home_coef','draw_coef','away_coef']
rcategory=['Division','Referee','Time']
rnumeric=['full_time_home_goals', 'full_time_away_goals','half_time_home_goals','half_time_away_goals','home_team','away_team']
rfloating=['home_coef','draw_coef','away_coef']
#-1
put=['home_shots','away_shots','home_shots_on_target','away_shots_on_target','home_fouls','away_fouls','home_corners','away_corners','home_yellow_cards','away_yellow_cards','home_red_cards','away_red_cards']

In [21]:
#df_train.iloc[:,:-1]=df_train.iloc[:,:-1].fillna('-1')
print(len(rcategory)+len(rnumeric)+len(rfloating))
print(len(respective))
print(len(put))

12
12
12


In [22]:
df_trainc=df_train.copy()

In [31]:
for col in rnumeric:
    df_trainc[col]=df_trainc.fillna(df_trainc[col].mean())
for col in rfloating:
    df_trainc[col]=df_trainc.fillna(df_trainc[col].mean())
for col in put:
    df_trainc[col]=df_trainc.fillna('-1')
    df_trainc[col]=df_trainc[col].astype(float)

In [32]:
df_trainc.iloc[:,-1].mode()

0   -0.387802
dtype: float64

In [33]:
df_trainc.iloc[:,-1]=df_train.iloc[:,-1].apply(lambda x: str(x).replace('nan','-0.387802'))

In [34]:
df_trainc.iloc[:,-1]=df_train.iloc[:,-1].astype(float)

In [35]:
df_trainc

Division  Time  home_team  away_team  full_time_home_goals  \
0             0    -1        0.0        0.0                   0.0   
1             0    -1        0.0        0.0                   0.0   
2             0    -1        0.0        0.0                   0.0   
3             0    -1        0.0        0.0                   0.0   
4             1    -1        1.0        1.0                   1.0   
...         ...   ...        ...        ...                   ...   
39987        15    -1       15.0       15.0                  15.0   
39988        15    -1       15.0       15.0                  15.0   
39989        15    -1       15.0       15.0                  15.0   
39990        13    -1       13.0       13.0                  13.0   
39991         6    -1        6.0        6.0                   6.0   

       full_time_away_goals  half_time_home_goals  half_time_away_goals  \
0                       0.0                   0.0                   0.0   
1                       0.0                   0.0                   0.0   
2                       0.0                   0.0                   0.0   
3                       0.0                   0.0                   0.0   
4                       1.0                   1.0                   1.0   
...                     ...                   ...                   ...   
39987                  15.0                  15.0                  15.0   
39988                  15.0                  15.0                  15.0   
39989                  15.0                  15.0                  15.0   
39990                  13.0                  13.0                  13.0   
39991                   6.0                   6.0                   6.0   

       Referee  home_shots  ...  home_corners  away_corners  \
0           -1         0.0  ...           0.0           0.0   
1           -1         0.0  ...           0.0           0.0   
2           -1         0.0  ...           0.0           0.0   
3           -1         0.0  ...           0.0           0.0   
4           -1         1.0  ...           1.0           1.0   
...        ...         ...  ...           ...           ...   
39987       -1        15.0  ...          15.0          15.0   
39988       -1        15.0  ...          15.0          15.0   
39989       -1        15.0  ...          15.0          15.0   
39990       -1        13.0  ...          13.0          13.0   
39991       -1         6.0  ...           6.0           6.0   

       home_yellow_cards  away_yellow_cards  home_red_cards  away_red_cards  \
0                    0.0                0.0             0.0             0.0   
1                    0.0                0.0             0.0             0.0   
2                    0.0                0.0             0.0             0.0   
3                    0.0                0.0             0.0             0.0   
4                    1.0                1.0             1.0             1.0   
...                  ...                ...             ...             ...   
39987               15.0               15.0            15.0            15.0   
39988               15.0               15.0            15.0            15.0   
39989               15.0               15.0            15.0            15.0   
39990               13.0               13.0            13.0            13.0   
39991                6.0                6.0             6.0             6.0   

       home_coef  draw_coef  away_coef  away_shots_on_target.1  
0            0.0        0.0        0.0               -0.387802  
1            0.0        0.0        0.0               -0.387802  
2            0.0        0.0        0.0               -0.387802  
3            0.0        0.0        0.0               -0.387802  
4            1.0        1.0        1.0               -1.032101  
...          ...        ...        ...                     ...  
39987       15.0       15.0       15.0               -0.049414  
39988       15.0       15.0       15.0             

In [342]:
#for i in category:
#    X_train[i]=X_train[i].astype(object)

In [343]:
#for col in numeric:
#    X_train[col]=X_train.astype(int)

In [344]:
#for col in floating:
#    X_train[col]=X_train.astype(float)

In [60]:
df_trainc.Time=df_trainc.Time.astype(str)
df_trainc.Division=df_trainc.Division.astype(str)
df_trainc.Referee=df_trainc.Referee.astype(str)
df_trainc.dtypes

Division                   object
Time                       object
home_team                 float64
away_team                 float64
full_time_home_goals      float64
full_time_away_goals      float64
half_time_home_goals      float64
half_time_away_goals      float64
Referee                    object
home_shots                float64
away_shots                float64
home_shots_on_target      float64
away_shots_on_target      float64
home_fouls                float64
away_fouls                float64
home_corners              float64
away_corners              float64
home_yellow_cards         float64
away_yellow_cards         float64
home_red_cards            float64
away_red_cards            float64
home_coef                 float64
draw_coef                 float64
away_coef                 float64
away_shots_on_target.1    float64
dtype: object

In [61]:
X_train=df_trainc[['Division','Time','home_team','away_team','Referee','home_coef','draw_coef','away_coef','full_time_home_goals','full_time_away_goals','half_time_home_goals','half_time_away_goals','home_shots','away_shots','home_shots_on_target','away_shots_on_target','home_fouls','away_fouls','home_corners','away_corners','home_yellow_cards','away_yellow_cards','home_red_cards','away_red_cards']]
y_train=df_trainc.iloc[:,-1].values

In [62]:
X_train

Division Time  home_team  away_team Referee  home_coef  draw_coef  \
0            0   -1        0.0        0.0      -1        0.0        0.0   
1            0   -1        0.0        0.0      -1        0.0        0.0   
2            0   -1        0.0        0.0      -1        0.0        0.0   
3            0   -1        0.0        0.0      -1        0.0        0.0   
4            1   -1        1.0        1.0      -1        1.0        1.0   
...        ...  ...        ...        ...     ...        ...        ...   
39987       15   -1       15.0       15.0      -1       15.0       15.0   
39988       15   -1       15.0       15.0      -1       15.0       15.0   
39989       15   -1       15.0       15.0      -1       15.0       15.0   
39990       13   -1       13.0       13.0      -1       13.0       13.0   
39991        6   -1        6.0        6.0      -1        6.0        6.0   

       away_coef  full_time_home_goals  full_time_away_goals  ...  \
0            0.0                   0.0                   0.0  ...   
1            0.0                   0.0                   0.0  ...   
2            0.0                   0.0                   0.0  ...   
3            0.0                   0.0                   0.0  ...   
4            1.0                   1.0                   1.0  ...   
...          ...                   ...                   ...  ...   
39987       15.0                  15.0                  15.0  ...   
39988       15.0                  15.0                  15.0  ...   
39989       15.0                  15.0                  15.0  ...   
39990       13.0                  13.0                  13.0  ...   
39991        6.0                   6.0                   6.0  ...   

       home_shots_on_target  away_shots_on_target  home_fouls  away_fouls  \
0                       0.0                   0.0         0.0         0.0   
1                       0.0                   0.0         0.0         0.0   
2                       0.0                   0.0         0.0         0.0   
3                       0.0                   0.0         0.0         0.0   
4                       1.0                   1.0         1.0         1.0   
...                     ...                   ...         ...         ...   
39987                  15.0                  15.0        15.0        15.0   
39988                  15.0                  15.0        15.0        15.0   
39989                  15.0                  15.0        15.0        15.0   
39990                  13.0                  13.0        13.0        13.0   
39991                   6.0                   6.0         6.0         6.0   

       home_corners  away_corners  home_yellow_cards  away_yellow_cards  \
0               0.0           0.0                0.0                0.0   
1               0.0           0.0                0.0                0.0   
2               0.0           0.0                0.0                0.0   
3               0.0           0.0                0.0                0.0   
4               1.0           1.0                1.0                1.0   
...             ...           ...                ...                ...   
39987          15.0          15.0               15.0               15.0   
39988          15.0          15.0               15.0               15.0   
39989          15.0          15.0               15.0               15.0   
39990          13.0          13.0               13.0               13.0   
39991           6.0           6.0                6.0                6.0   

       home_red_cards  away_red_cards  
0                 0.0             0.0  
1                 0.0             0.0  
2                 0.0             0.0  
3                 0.0             0.0  
4                 1.0             1.0  
...               ...             ...  
39987            15.0            15.0  
39988            15.0            15.0  
39989            15.0            15.0  
39990            13.0            13.0  
39991     

In [63]:
y_train

array([-0.387802  , -0.387802  , -0.387802  , ..., -0.36218294,
       -1.21662169,  0.40666494])

In [64]:
X_train.shape

(39992, 24)

In [65]:
y_train.shape

(39992,)

In [66]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1.fit(X_train, y_train)

LinearRegression()

In [76]:
# Predicting the Test set results
arr=[]
y_pred1 = regressor1.predict([[0,-1,152,426,1,3.627689584601,3.577721408504,2.198599748243,0,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]])
ev2=regressor1.predict(X_train)
arr.append(y_pred1)
y_pred1

array([-4.37328695e+10])

In [77]:
# Predicting the Test set results
y_pred2 = regressor1.predict([[1,-1,141,217,-1,1.714712084927,4.034616670416,5.587944088527,3,0,1,0,17,6,11,2,11,16,10,3,0,1,0,0]])
ev2=regressor1.predict(X_train)
arr.append(y_pred2)
y_pred2

array([-8.0791365e+11])

In [78]:
# Predicting the Test set results
y_pred3 = regressor1.predict([[17,19,333,444,7,3.242665536417,3.714271486813,2.242156197892,2,4,1,0,7,12,4,8,11,-1,-1,-1,-1,-1,-1,0]])
ev3=regressor1.predict(X_train)
arr.append(y_pred3)
y_pred3

array([2.43701004e+12])

In [112]:
import sys
import time
for i in arr:
    if i<0 and i <-5:
        print("DRAW",flush=True)
        time.sleep(1)
    elif i<0 and i>-8:
        print("HOME",flush=True)
        time.sleep(1)
    else:
        if i>0:
            print("AWAY",flush=True)
            time.sleep(1)      

DRAW
DRAW
AWAY
